export type BankPhrase = {
  text: string;
  points: 1 | 2 | 3 | 4;
};

/** Original party-game phrases in the spirit of Monikers — not copied cards. */
export const PHRASE_BANK: BankPhrase[] = [
  { text: "Pizza", points: 1 },
  { text: "The Moon", points: 1 },
  { text: "Superman", points: 1 },
  { text: "Santa Claus", points: 1 },
  { text: "Basketball", points: 1 },
  { text: "Sunglasses", points: 1 },
  { text: "Birthday cake", points: 1 },
  { text: "The Beatles", points: 1 },
  { text: "Google", points: 1 },
  { text: "Coffee", points: 1 },
  { text: "Ice cream", points: 1 },
  { text: "Shark", points: 1 },
  { text: "Guitar", points: 1 },
  { text: "Airplane", points: 1 },
  { text: "Rainbow", points: 1 },
  { text: "Halloween", points: 1 },
  { text: "Soccer", points: 1 },
  { text: "Smartphone", points: 1 },
  { text: "Hot dog", points: 1 },
  { text: "Batman", points: 1 },
  { text: "Unicorn", points: 1 },
  { text: "Selfie", points: 1 },
  { text: "Dinosaur", points: 1 },
  { text: "Fireworks", points: 1 },
  { text: "Robot", points: 1 },
  { text: "Moonwalk", points: 2 },
  { text: "The Olympics", points: 2 },
  { text: "Escape room", points: 2 },
  { text: "Air guitar", points: 2 },
  { text: "Fortune cookie", points: 2 },
  { text: "Slow clap", points: 2 },
  { text: "Plot twist", points: 2 },
  { text: "Food truck", points: 2 },
  { text: "Binge-watching", points: 2 },
  { text: "Jump scare", points: 2 },
  { text: "Red carpet", points: 2 },
  { text: "Brain freeze", points: 2 },
  { text: "Dad joke", points: 2 },
  { text: "Viral video", points: 2 },
  { text: "Happy hour", points: 2 },
  { text: "Bigfoot", points: 2 },
  { text: "Area 51", points: 2 },
  { text: "Mona Lisa", points: 2 },
  { text: "Stonehenge", points: 2 },
  { text: "The Sphinx", points: 2 },
  { text: "Karaoke", points: 2 },
  { text: "Inflatable flamingo", points: 2 },
  { text: "The wave (crowd)", points: 2 },
  { text: "Wi-Fi password", points: 2 },
  { text: "Road trip", points: 2 },
  { text: "Surprise party", points: 2 },
  { text: "Mic drop", points: 2 },
  { text: "Drumroll", points: 2 },
  { text: "High five", points: 2 },
  { text: "Time-out", points: 2 },
  { text: "Parallel parking", points: 3 },
  { text: "Small talk", points: 3 },
  { text: "Impostor syndrome", points: 3 },
  { text: "The friend zone", points: 3 },
  { text: "Catch-22", points: 3 },
  { text: "Déjà vu", points: 3 },
  { text: "Murphy's Law", points: 3 },
  { text: "The butterfly effect", points: 3 },
  { text: "Schrödinger's cat", points: 3 },
  { text: "The Trojan Horse", points: 3 },
  { text: "Bermuda Triangle", points: 3 },
  { text: "Midlife crisis", points: 3 },
  { text: "Method acting", points: 3 },
  { text: "Elevator pitch", points: 3 },
  { text: "Looking busy at work", points: 3 },
  { text: "The last slice of pizza", points: 3 },
  { text: "A plot hole", points: 3 },
  { text: "Hot mic", points: 3 },
  { text: "Group project", points: 3 },
  { text: "Out-of-office reply", points: 3 },
  { text: "Read receipt", points: 3 },
  { text: "The algorithm", points: 3 },
  { text: "Existential crisis", points: 3 },
  { text: "Passive-aggressive note", points: 3 },
  { text: "A Pyrrhic victory", points: 4 },
  { text: "The Ship of Theseus", points: 4 },
  { text: "Kafkaesque", points: 4 },
  { text: "Petrichor", points: 4 },
  { text: "Schadenfreude", points: 4 },
  { text: "A Rube Goldberg machine", points: 4 },
  { text: "The Streisand effect", points: 4 },
  { text: "The trolley problem", points: 4 },
  { text: "Occam's razor", points: 4 },
  { text: "A MacGuffin", points: 4 },
  { text: "Liminal space", points: 4 },
  { text: "Onomatopoeia", points: 4 },
  { text: "A palindrome", points: 4 },
  { text: "Deus ex machina", points: 4 },
  { text: "A red herring", points: 4 },
  { text: "The uncanny valley", points: 4 },
  { text: "A white elephant gift", points: 4 },
  { text: "Ennui", points: 4 },
  { text: "A Sisyphean task", points: 4 },
  { text: "The Baader-Meinhof phenomenon", points: 4 },
  { text: "A Gordian knot", points: 4 },
];

export const PHRASE_BANK_SIZE = PHRASE_BANK.length;
